; This file was generated by EFESTO v.2.0
;
; Text file: test/01-horizontal-range-index.clj
; Excel File: test/01-horizontal-range-index.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; B1 = 0.0
; C1 = 1.0
; D1 = 2.0
; E1 = 3.0
; F1 = 4.0
; G1 = 5.0
; H1 = 6.0
; HORIZONTAL_RANGE!B5 = INDEX(B1:H1,3)
; A7 = 
; END-RAW-TEXT
(def B1:H1 [ 0.0 1.0 2.0 3.0 4.0 5.0 6.0 ])
(def B5 (index B1:H1 3))
