; This file was generated by EFESTO v.2.0
;
; Text file: test/02-vertical-range-index.clj
; Excel File: test/02-vertical-range-index.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; B1 = 
; C1 = 
; D1 = 
; E1 = 
; F1 = 
; G1 = 
; H1 = 
; I1 = 0.0
; I2 = 1.0
; I3 = 2.0
; I4 = 3.0
; I5 = 4.0
; I6 = 5.0
; A7 = 
; I7 = 6.0
; VERTICAL_RANGE!B9 = INDEX(I1:I7,4)
; END-RAW-TEXT
(def I1:I7 [ 0.0 1.0 2.0 3.0 4.0 5.0 6.0 ])
(def B9 (index I1:I7 4))
