; This file was generated by EFESTO v.2.0
;
; Text file: test/03-range-index.clj
; Excel File: test/03-range-index.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.1
; B1 = 1.2
; C1 = 
; D1 = 
; E1 = 
; F1 = 
; G1 = 
; A2 = 2.1
; B2 = 2.2
; A3 = 3.1
; B3 = 3.2
; A4 = 4.1
; B4 = 4.2
; A5 = 5.1
; B5 = 5.2
; A6 = 6.1
; B6 = 6.2
; A7 = 
; RANGE!A10 = INDEX(A1:B6,2,2)
; END-RAW-TEXT
(def A1:B6 [[1.1 1.2][2.1 2.2][3.1 3.2][4.1 4.2][5.1 5.2][6.1 6.2]])
(def A10 (index A1:B6 2 2))
