; This file was generated by EFESTO v.2.0
;
; Text file: test/07-FunctionCall.clj
; Excel File: test/07-FunctionCall.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; B1 = 2.0
; C1 = 3.0
; D1 = 
; E1 = 
; FunctionCall!A2 = SUM(A1:C1)
; END-RAW-TEXT
(def A1:C1 [ 1.0 2.0 3.0 ])
(def A2 (reduce + A1:C1))
