; This file was generated by EFESTO v.2.0
;
; Text file: test/08-BinaryOp.clj
; Excel File: test/08-BinOp.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = a
; B1 = 1.0
; A2 = b
; B2 = 3.0
; A3 = c=b-a
; BinOp!B3 = B2-B1
; END-RAW-TEXT
(def B1 1.0)
(def B2 3.0)
(def B3 (- B2 B1))
