; This file was generated by EFESTO v.2.0
;
; Text file: test/09-Expr.clj
; Excel File: test/09-Expr.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 100.0
; Expr!A2 = (A1*2)/2
; END-RAW-TEXT
(def A1 100.0)
(def A2 (/ ((* A1 2)) 2))
