; This file was generated by EFESTO v.2.0
; Created:2026-06-01T09:42:28.686716400
;
; Text file: test/10-Prefix.clj
; Excel File: test/10-Prefix.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; Prefix!A1 = Sheet1!A1
; END-RAW-TEXT
(def Sheet1!A1 78.0)
(def Prefix!A1 Sheet1!A1)
