; This file was generated by EFESTO v.2.0
;
; Text file: test/11-UnOpPrefix.clj
; Excel File: test/11-UnOpPrefix.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 13.0
; UnOpPrefix!A2 = +A1+1
; END-RAW-TEXT
(def UnOpPrefix!A1 +13.0)
(def A2 (+ UnOpPrefix!A1 1))
