; This file was generated by EFESTO v.2.0
;
; Text file: test/12-String-COUNTIF.clj
; Excel File: test/12-String-COUNTIF.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; C1 = 1.0
; D1 = 2.0
; E1 = 3.0
; COUNTIF!B4 = COUNTIF(C1:E1,">=2")
; END-RAW-TEXT
(def C1:E1 [ 1.0 2.0 3.0 ])
(def B4 (countif C1:E1 ">=2"))
