; This file was generated by EFESTO v.2.0
;
; Text file: test/13-NamedRange.clj
; Excel File: test/13-NamedRange.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; A2 = 2.0
; A3 = 3.0
; A4 = 4.0
; A5 = 5.0
; A6 = 6.0
; NamedRange!A8 = SUM(slist)
; END-RAW-TEXT
(def NamedRange!slist [ 1.0 2.0 3.0 4.0 5.0 6.0 ])
(def A8 (reduce + NamedRange!slist))
