;
; Efesto - Excel Formula Extractor System and Topological Ordering algorithm.
; Copyright (C) 2017 Massimo Caliman mcaliman@gmail.com
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU Affero General Public License as published
; by the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU Affero General Public License for more details.
;
; You should have received a copy of the GNU Affero General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
; If AGPL Version 3.0 terms are incompatible with your use of
; Efesto, alternative license terms are available from Massimo Caliman
; please direct inquiries about Efesto licensing to mcaliman@gmail.com
;

; This file was generated by EFESTO v.2.0
;
; Text file: test/15-Others-FUN.clj
; Excel File: test/15-Others-FUN.xlsx
; Excel Formulas Number: 8
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = FILE 
; Foglio1!G1 = [1]Sheet1!C5
; A2 = REFERENCE-FUNCTION 
; D2 = =SUM(J9:INDEX(J9:J41,B43)) 
; A3 = QUOTED-FILE-SHEET 
; D3 = =(’[2]Detail I&E’!D62)/1000 
; A4 = UDF 
; G4 = =SQRT(_eoq2(C5,C4,C6,C7)) 
; A5 = ’_xll.’ 
; F5 = =_xll.RiskTriang(F9,F7,F8) 
; A6 = ERROR_REF 
; F6 = =AVERAGE(#REF!) 
; A7 = (’ <Reference> ’)’ 
; Foglio1!D7 = (2*(B29))/(1+B29)
; A8 = VERTICAL-RANGE 
; Foglio1!E8 = _xludf.COUNT(A:A)
; A9 = FILE ’!’ 
; F9 = =[1]!today 
; A10 = ERROR 
; G10 = =IF(AND(R11=1,R14=TRUE),G19,0) 
; A11 = ’%’ 
; G11 = =IF(E5>I8,3%,0%) 
; A12 = Empty argument 
; E12 = =DCOUNT(Lettergrades„I80:I81) 
; A13 = Complex range 
; Foglio1!E13 = _xludf.SUM(I8:K8:M8)
; A14 = <DynamicDataExchange> 
; Foglio1!C14 = [2]!’NGH2 NET.CHNG”
; A15 = Intersection 
; E15 = =Ending_Inventory Jan 29
; A16 = MULTIPLE-SHEETS 
; Foglio1!D16 = _xludf.SUM(Sheet1:'[3]Sheet20'!I29)
; A18 = Prefixed right reference limit 
; Foglio1!B18 = _xludf.SUM(’Tot-'[4]1’'!$B8:’Tot-'[4]1’'!B8)
; A19 = RESERVED_NAME 
; Foglio1!F19 = C23/_xlnm.Print_Area
; A20 = UDF reference 
; F20 = =[1]!wbname() 
; A21 = HORIZONTAL-RANGE 
; E21 = =MATCH(F3,Prices!2:2,0) 
; A22 = <Union> 
; G22 = =LARGE((F38,C38),1) 
; A23 = <ConstantArray> 
; E23 = =FVSCHEDULE(1,0.09;0.11;0.1) 
; B29 = 70.0
; END-RAW-TEXT
(def G1 [1] Sheet1!C5)
(def B29 70.0)
(def D7 (/ ((* 2 (B29))) ((+ 1 B29))))
