; This file was generated by EFESTO v.2.0
;
; Text file: test/16-example-range-1.clj
; Excel File: test/16-example-range-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; D3 = 0.0
; E3 = 1.0
; F3 = 2.0
; G3 = 3.0
; H3 = 4.0
; Foglio1!D7 = INDEX(D3:H3,2)
; END-RAW-TEXT
(def D3:H3 [ 0.0 1.0 2.0 3.0 4.0 ])
(def D7 (index D3:H3 2))
