; This file was generated by EFESTO v.2.0
;
; Text file: test/17-IF-into-IF.clj
; Excel File: test/17-IF-into-IF.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; IFIF!A1 = IF(B1>1,0,IF(C1,"Hello","Bye"))
; B1 = 2.0
; C1 = TRUE
; END-RAW-TEXT
(def B1 2.0)
(def C1 Boolean/TRUE)
(def A1 (if (> B1 1) 0 (if C1 "Hello" "Bye")))
