; This file was generated by EFESTO v.2.0
;
; Text file: test/18-matrix-1.clj
; Excel File: test/18-matrix-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; B1 = 2.0
; C1 = 3.0
; D1 = 4.0
; A2 = 4.0
; B2 = 6.0
; C2 = 7.0
; D2 = 8.0
; A4 = 2.0
; Foglio1!B7 = INDEX(A1:D2,1,1)
; END-RAW-TEXT
(def A1:D2 [[1.0 2.0 3.0 4.0][4.0 6.0 7.0 8.0]])
(def B7 (index A1:D2 1 1))
