; This file was generated by EFESTO v.2.0
;
; Text file: test/901-terminals.clj
; Excel File: test/901-terminals.xlsx
; Excel Formulas Number: 5
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; Foglio1!A1 = TRUE
; Foglio1!A2 = 1.838226
; Foglio1!A3 = 24
; Foglio1!A4 = "This is a string"
; Foglio1!A5 = 1/0
; END-RAW-TEXT
(def A5 (/ 1 0))
