; This file was generated by EFESTO v.2.0
;
; Text file: test/902-terminals-formulas.clj
; Excel File: test/902-terminals-formulas.xlsx
; Excel Formulas Number: 4
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = TRUE
; A2 = 1.838226
; A3 = 24.0
; A4 = This is a string
; Foglio1!A5 = 1/0
; Foglio1!A7 = IF(A1,A2,A3)
; Foglio1!A8 = IF(A1,A4,A7)
; Foglio1!A9 = IF(A1,A5,A3)
; END-RAW-TEXT
(def A1 Boolean/TRUE)
(def A5 "1/0")
(def A3 24.0)
(def A4 "This is a string")
(def A2 1.838226)
(def A9 (if A1 A5 A3))
(def A7 (if A1 A2 A3))
(def A8 (if A1 A4 A7))
