; This file was generated by EFESTO v.2.0
;
; Text file: test/903-terminals-formulas.clj
; Excel File: test/903-terminals-formulas.xlsx
; Excel Formulas Number: 2
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = TRUE
; A2 = 1.838226
; A3 = 24.0
; A4 = This is a string
; Foglio1!A6 = IF(A1,A2,A3)
; Foglio1!A7 = IF(A1,A4,A3)
; END-RAW-TEXT
(def A1 Boolean/TRUE)
(def A2 1.838226)
(def A3 24.0)
(def A4 "This is a string")
(def A6 (if A1 A2 A3))
(def A7 (if A1 A4 A3))
