; This file was generated by EFESTO v.2.0
;
; Text file: test/904-terminals-formulas.clj
; Excel File: test/904-terminals-formulas.xlsx
; Excel Formulas Number: 6
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 10.0
; B1 = A1
; A2 = 20.0
; B2 = A2
; Foglio1!A3 = A1+A2
; B3 = A1+A2
; Foglio1!A4 = A1-A2
; B4 = A1-A2
; Foglio1!A5 = A1*A2
; B5 = A1*A2
; Foglio1!A6 = A1/A2
; B6 = A1/A2
; Foglio1!A7 = A1&A2
; B7 = A1&A2
; Foglio1!A8 = A1^A2
; B8 = A1^A2
; END-RAW-TEXT
(def A2 20.0)
(def A1 10.0)
(def A4 (- A1 A2))
(def A5 (* A1 A2))
(def A6 (/ A1 A2))
(def A3 (+ A1 A2))
(def A8 (Math/pow A1 A2))
(def A7 (str A1 A2))
