; This file was generated by EFESTO v.2.0
;
; Text file: test/area-1.clj
; Excel File: test/area-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 11.0
; B1 = 21.0
; A2 = 12.0
; B2 = 22.0
; A3 = 13.0
; B3 = 23.0
; Area1!A7 = INDEX(A1:B3,2,2)
; END-RAW-TEXT
(def A1:B3 [[11.0 21.0][12.0 22.0][13.0 23.0]])
(def A7 (index A1:B3 2 2))
