; This file was generated by EFESTO v.2.0
; Created:2026-06-01T10:25:57.633416400
;
; Text file: test/comments.clj
; Excel File: test/comments.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; Sheet1!A2 = A1+1
; END-RAW-TEXT
(def A1 1.0)
(def A2 (+ A1 1))
