; This file was generated by EFESTO v.2.0
;
; Text file: test/ConstantArray.clj
; Excel File: test/ConstantArray.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; A2 = 2.0
; A3 = 2.0
; A4 = 4.0
; A5 = 6.0
; Foglio1!A6 = {1;2;2;4;6}
; END-RAW-TEXT
(def Foglio1!A6 [1.0 2.0 2.0 4.0 6.0])
