; This file was generated by EFESTO v.2.0
;
; Text file: test/file-1.clj
; Excel File: test/file-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; SrcSheet!A1 = [1]DestSheet!$A$1
; END-RAW-TEXT
(def A1 [1]DestSheet!$A$1)
