; This file was generated by EFESTO v.2.0
;
; Text file: test/HORIZONTAL_RANGE.clj
; Excel File: test/HORIZONTAL_RANGE.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 1.0
; B1 = 3.0
; C1 = 6.0
; D1 = 8.0
; Foglio1!A3 = MATCH(3,A1:D1,0)
; END-RAW-TEXT
(def A1:D1 [ 1.0 3.0 6.0 8.0 ])
(def A3 (match 3 A1:D1 0))
