; This file was generated by EFESTO v.2.0
;
; Text file: test/metadata.clj
; Excel File: test/metadata.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 12.0
; Foglio1!A2 = A1+1
; END-RAW-TEXT
(def A1 12.0)
(def A2 (+ A1 1))
