; This file was generated by EFESTO v.2.0
;
; Text file: test/multisheet-1.clj
; Excel File: test/multisheet-1.xlsx
; Excel Formulas Number: 1
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; SheetA!A1 = SUM(SheetB!A1:A3)
; A1 = 1.0
; A2 = 2.0
; A3 = 3.0
; END-RAW-TEXT
(def SheetB!A1:A3 [ 1.0 2.0 3.0 ])
(def SheetA!A1 (reduce + SheetB!A1:A3))
