; This file was generated by EFESTO v.2.0
;
; Text file: test/SHEET-QUOTED.clj
; Excel File: test/SHEET-QUOTED.xlsx
; Excel Formulas Number: 2
; Elapsed Time (parsing + topological sort): 0 s. or 0 min.
;
; BEGIN-RAW-TEXT
; A1 = 10.0
; Sheet Name With Spaces!A2 = A1+10
; A1 = 30.0
; Other Sheet Name With Spaces!A2 = A1+30
; END-RAW-TEXT
(def 'Other Sheet Name With Spaces'!A1 30.0)
(def 'Sheet Name With Spaces'!A1 10.0)
(def 'Other Sheet Name With Spaces'!A2 (+ 'Other Sheet Name With Spaces'!A1 30))
(def 'Sheet Name With Spaces'!A2 (+ 'Sheet Name With Spaces'!A1 10))
